services:
  - docker

before_install:
  - docker build -t dev -f Dockerfile.dev .
  - docker build -t prod .

script:
  - docker run --name dev-app -d -p 8000:3000 dev
  - docker stop dev-app
  - docker run --name prod-app -d -p 80:80 prod
  - docker stop prod-app